# Generated by Django 3.2.6 on 2021-08-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieadmin', '0013_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
