# Generated by Django 3.2.6 on 2021-08-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieadmin', '0015_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
