# Generated by Django 3.2.6 on 2021-08-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieadmin', '0016_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
